GET http://localhost:3000/products

###
GET http://localhost:3000/products/1
###
POST http://localhost:3000/products
Content-Type: application/json

{
    "title": "Product 2",
    "price": 899
}
###
PATCH http://localhost:3000/products/1
Content-Type: application/json

{
    "title": "Product Updated",
    "price": 900
}

###
DELETE  http://localhost:3000/products/1
